# Generated by Django 5.0.6 on 2024-06-15 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_category_product_sub_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SoldProduct',
            new_name='InvoiceItem',
        ),
    ]
