# Generated by Django 5.0.6 on 2024-06-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_soldproduct_invoiceitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceBill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sold_product', models.ManyToManyField(to='product.invoiceitem')),
            ],
        ),
        migrations.DeleteModel(
            name='DailySalesReport',
        ),
    ]
