# Generated by Django 5.0.6 on 2024-06-16 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_invoicebill_delete_dailysalesreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicebill',
            name='bill_for',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='invoicebill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 6, 16, 14, 5, 49, 742178, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoicebill',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
    ]
