# Generated by Django 5.0.6 on 2024-06-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_invoicebill_bill_for_invoicebill_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicebill',
            name='is_printed',
            field=models.BooleanField(default=False),
        ),
    ]
