# Generated by Django 5.0.6 on 2024-06-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_invoicebill_is_printed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicebill',
            old_name='sold_product',
            new_name='Invoice_Item',
        ),
        migrations.AddField(
            model_name='invoicebill',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
