# Generated by Django 5.0.6 on 2024-06-16 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_rename_sold_product_invoicebill_invoice_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='in_stock',
        ),
    ]
