# Generated by Django 5.0.6 on 2024-06-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_rename_quantity_product_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicebill',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
