# Generated by Django 5.0.6 on 2024-06-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_invoicebill_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicebill',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
