# Generated by Django 5.0.6 on 2024-06-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_invoiceitem_sold_out'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelayPenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay_duration', models.DurationField()),
                ('penalty_duration', models.DurationField()),
                ('penalty_deduction', models.CharField(max_length=100)),
            ],
        ),
    ]
