# Generated by Django 5.0.6 on 2024-06-29 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_delaypenalty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DelayPenalty',
        ),
    ]
