# Generated by Django 5.0.6 on 2024-06-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_delete_delaypenalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicebill',
            name='credit_amt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicebill',
            name='paid_amt',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
