# Generated by Django 5.0.6 on 2024-06-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_invoicebill_credit_amt_invoicebill_paid_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicebill',
            name='address',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='invoicebill',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='invoicebill',
            name='mode_of_payment',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='invoicebill',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
