# Generated by Django 5.0.6 on 2024-06-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_invoicebill_address_invoicebill_invoice_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicebill',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
