# Generated by Django 5.0.6 on 2024-06-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_invoicebill_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicebill',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
