# Generated by Django 5.0.6 on 2024-07-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_invoicebill_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicebill',
            name='mode_of_payment',
            field=models.CharField(blank=True, choices=[('cash', 'cash'), ('credit', 'credit'), ('ONLINE', 'Online'), ('CHEQUE', 'Cheque')], max_length=250, null=True),
        ),
    ]
