# Generated by Django 5.0.6 on 2024-07-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_invoicebill_mode_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicebill',
            name='contact_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
