# Generated by Django 5.0.6 on 2024-07-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_invoicebill_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicebill',
            name='invoice_miti',
            field=models.DateField(blank=True, null=True),
        ),
    ]
