# Generated by Django 5.0.6 on 2024-07-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_invoicebill_invoice_miti'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicebill',
            name='np_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicebill',
            name='np_updated_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
