# Generated by Django 5.0.6 on 2024-07-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_invoicebill_np_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicebill',
            name='unit',
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, null=True),
        ),
    ]
