# Generated by Django 5.0.6 on 2024-07-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_remove_invoicebill_unit_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicebill',
            name='code',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
