# Generated by Django 5.0.6 on 2024-07-14 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_invoicebill_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicebill',
            old_name='np_created_at',
            new_name='invoice_date',
        ),
        migrations.RemoveField(
            model_name='invoicebill',
            name='np_updated_date',
        ),
    ]
