# Generated by Django 5.0.6 on 2024-07-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_rename_np_created_at_invoicebill_invoice_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicebill',
            name='invoice_miti',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
