# Generated by Django 5.0.6 on 2024-07-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_alter_invoicebill_invoice_miti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicebill',
            name='invoice_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoicebill',
            name='invoice_miti',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
