# Generated by Django 5.0.6 on 2024-07-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_alter_invoicebill_invoice_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicebill',
            name='code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
