# Generated by Django 5.0.6 on 2024-07-14 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_alter_invoicebill_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicebill',
            old_name='code',
            new_name='invoice_no',
        ),
    ]
