# Generated by Django 5.0.6 on 2024-07-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_remove_invoicebill_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicebill',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
