# Generated by Django 5.0.6 on 2024-07-14 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_invoicebill_invoice_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicebill',
            name='invoice_no',
        ),
    ]
