# Generated by Django 5.0.6 on 2024-07-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_invoicebill_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='invoice_miti',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
