# Generated by Django 5.0.6 on 2024-07-26 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_passwordresetcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingInvoiceBillId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
