# Generated by Django 5.0.6 on 2024-08-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_importproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='importproduct',
            name='mode_of_payment',
            field=models.CharField(blank=True, choices=[('cash', 'cash'), ('credit', 'credit'), ('ONLINE', 'Online'), ('CHEQUE', 'Cheque')], max_length=250, null=True),
        ),
    ]
