# Generated by Django 5.0.6 on 2024-08-03 13:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_importproduct_mode_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicebill',
            name='pdf',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
