# Generated by Django 5.0.6 on 2024-08-05 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_invoicebill_bill_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicebill',
            name='pdf',
        ),
    ]
